services:
  catalogapi:
     build:
        context: ./src/Services/Catalog/EShop.Service.CatalogAPI
        dockerfile: Dockerfile
     environment:
        - ASPNETCORE_ENVIRONMENT=Production
     ports:
        - "8080:8080"
     depends_on:
        - catalogdb
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=EShopCatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/  