services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server

volumes:
  postgres_catalog:
  postgres_basket:  